# Determinan 

Determinan matriks adalah nilai skalar yang dapat diperoleh dari suatu matriks persegi. Determinan memberikan informasi penting tentang sifat-sifat matriks tersebut. Untuk matriks persegi ${n × n}$, determinannya dinyatakan sebagai nilai numerik tunggal,

In [34]:
import numpy as np

## sifat sifat matriks

### 1.Determinan dari matriks ${I_{nxn}}$ adalah 1

In [35]:
I = np.identity(3)

print(I,"\n")

detI = np.linalg.det(I)

print(detI,"\n")

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

1.0 



### 2. Det(A^-1) adalah 1/det(A)


det(I) = det(A) * det(A^(-1))\

1 = det(A) * det(A^(-1))\

det(A^(-1)) = 1/det(A)

In [36]:
A = np.array([[1,2,3],[2,1,2],[3,2,1]])

invA = np.linalg.inv(A)
print(round(np.linalg.det(A)))

print(round(np.linalg.det(invA)))

print(round(1/np.linalg.det(A)))

8
0
0


### 3. Pengaruh Operasi Baris pada Determinan

menukar baris atau kolom suatu matriks mempengaruhi nilai determinan matriks tersebut


In [37]:
swapA1 = np.array([[2,1,2],[1,2,3],[3,2,1]])

swapA2 = np.array([[1,3,2],[2,2,1],[3,1,2]])

print(round(np.linalg.det(A)))
print(round(np.linalg.det(swapA1)))
print(round(np.linalg.det(swapA2)))

8
-8
-8


### 4. jika terdapat satu baris yang memiliki nilai kelipatan baris lain maka det = 0

In [38]:
B = np.array([[1,2,3],[3,6,9],[2,2,2]])

print(round(np.linalg.det(B)))

0


### 5. jika terdapat 2 baris stau colom yang sama maka nilai det =  0

In [39]:
C = np.array([[1,2,3],[2,2,2],[1,2,3]])

print(round(np.linalg.det(C)))

0


### 6. det(A^T) = det(A)

In [40]:
D = np.array([[1,2,3],[2,1,2],[3,2,1]])
Dt = np.transpose(D)

print(round(np.linalg.det(D)))
print(round(np.linalg.det(Dt)))

8
8


### 7. det(A = [x*a, x*b],  =  x det(A)
            [c  , d  ])

In [41]:
E = np.array([[1,2],[2,1]])
Ex1 = np.array([[2,4],[2,1]])
Ex2 = np.array([[1,2],[4,2]])

print(round(np.linalg.det(E)))
print(round(np.linalg.det(Ex1)))
print(round(np.linalg.det(Ex2)))

-3
-6
-6


### 8. Apabila ada sebuah skalar misal $K$ dikali dengan matriks A maka det(KA) = K^n det(A) yang mana n adalah ukuran dari matriks

In [42]:
F = np.array([[1,2,3],[2,1,2],[3,2,1]])
k = 2

print(round(np.linalg.det(F*k)))
print((k**3)*round(np.linalg.det(F)))

64
64


### 9. det dari matrix segitiga atas atau bawah adalah hasil dari perkalian dari diagonalnya

matrix segitiga adalah matrix yang sisi diagonal adalah 0 dan di sisi lain termasuk garis diagonal memiliki nilai >= 0

In [43]:
G = np.array([[1,2,3],[0,2,3],[0,0,3]])

print(round(np.linalg.det(G)))

6


## tugas mencari determinan menggunakan cofactor expansion