# Matrix
## operasi matrix menggunakan numpy

In [3]:
import numpy as np

In [2]:
# array ditentukan secara manual

A = np.array([[1,3],[2,1]])
B = np.array([[3,0,4],[-1,-2,-1]])
C = np.array([[-2,1],[4,1]])
D = np.array([[2],[6]])

print("Matrix A")
print(A,"\n")
print("Matrix B")
print(B,"\n")
print("Matrix C")
print(C,"\n")
print("Matrix D")
print(D,"\n")

Matrix A
[[1 3]
 [2 1]] 

Matrix B
[[ 3  0  4]
 [-1 -2 -1]] 

Matrix C
[[-2  1]
 [ 4  1]] 

Matrix D
[[2]
 [6]] 



In [3]:
# array ditentukan secara random

E = np.random.randint(10,size=(2,2))
F = np.random.randint(10,size=(3,2))
G = np.random.randint(10,size=(3,3))
print(E,"\n")
print(F,"\n")
print(G,"\n")

[[5 2]
 [8 4]] 

[[5 9]
 [0 9]
 [6 5]] 

[[7 7 5]
 [7 3 6]
 [5 1 7]] 



## Operasi matrix

In [4]:
# penjumlahan

# cek jumlah baris dan kolom matrix menggunakan shape
print(np.shape(A))

print(np.shape(C))
print()
# jika terdapat dua matrix yang memilik jumlah baris dan kolom yang sama maka kedua matrix tersebut dapat di jumlahkan
ac = A + C
print(ac)
# di operasi penjumlahan matrix juga berlaku sifat komunikatif
# (A + B) + C = A + (B + C)

(2, 2)
(2, 2)

[[-1  4]
 [ 6  2]]


In [5]:
# perkalian matrix dengan skalar

# C dan d adalah konnstanta dan A adalh matrix
c = 2
d = 4
A1 = (c + d) * A
print(A1, "\n")
print("Atau\n")
A2 = (c * A) + (d * A)
print(A2, "\n")

# berbeda cara tapi memiliki hasil yang sama

[[ 6 18]
 [12  6]] 

Atau

[[ 6 18]
 [12  6]] 



In [6]:
# Perkalian antar matrix

# Untuk mencari hasil kali matriks A dengan matriks B ialah dengan mengalikan elemen pada baris-baris matriks A 
# dengan elemen pada kolom-kolom matriks B, kemudian jumlahkan hasil perkalian antara baris dan kolom tersebut.





## perkalian matriks tanpa menggunakan numpy

In [5]:
listA = [
    [3,4],
    [2,5],
    [1,3]
    ]

listB = [
    [2,3,1],
    [1,4,3],
    ]
  
print("Matriks A",listA,"\n")
print("MAtriks B",listB,"\n")
print("panjang baris dan kolom")
print(len(listA),len(listA[0]),"\n")
print(len(listB),len(listB[0]),"\n")
n = len(listA)
m = len(listA[0])
p = len(listB[0])

hasil = []
for i in range(0,n):
  hasil1 = []
  for j in range(0,p):
    jumlah = 0
    for k in range(0,m):
      jumlah += listA[i][k] * listB[k][j]
    hasil1.append(jumlah)
  hasil.append(hasil1)
print("hasil dari perkalian matrix")
print(hasil,"\n")

Matriks A [[3, 4], [2, 5], [1, 3]] 

MAtriks B [[2, 3, 1], [1, 4, 3]] 

panjang baris dan kolom
3 2 

2 3 

hasil dari perkalian matrix
[[10, 25, 15], [9, 26, 17], [5, 15, 10]] 



## perkalian matriks menggunakan numpy

In [4]:
MatriksA = np.array(([3,4],[2,5],[1,3]))
MatriksB = np.array(([2,3,1],[1,4,3]))

print(MatriksA,"\n")
print(MatriksB,"\n")

dot1 = np.dot(MatriksA,MatriksB)
dot2 = MatriksA.dot(MatriksB)

print(dot1)
# print(dot2)

[[3 4]
 [2 5]
 [1 3]] 

[[2 3 1]
 [1 4 3]] 

[[10 25 15]
 [ 9 26 17]
 [ 5 15 10]]
