# Penyelesaian Persamaan Sistem Linier 

Sistem persamaan linear adalah sekumpulan persamaan linear yang terdiri dari beberapa variabel. Contohnya adalah:

\begin{align*} 
3x + 2y - z &=  1 \\ 
2x + 2y + 4z &=  -2\\
x + y + z &= 1
\end{align*}

Sistem ini terdiri dari tiga persamaan dengan tiga variabel x, y, z. Solusi sistem linear ini adalah nilai yang dapat menyelesaikan persamaan ini. Solusinya adalah:

\begin{align*} 
x &= 1\\
y &= -2\\
z &= -2
\end{align*}

## Eliminasi Gaussian

Eliminasi Gauss adalah algoritma yang digunakan untuk menyelesaikan sistem persamaan linear. Algoritma ini terdiri dari serangkaian operasi yang dilakukan pada matriks koefisien dari sistem persamaan tersebut.

Ada tiga jenis operasi baris dasar yang dapat dilakukan pada baris matriks tersebut:

1. Menukar posisi dua baris.
2. Mengalikan suatu baris dengan skalar bukan nol.
3. Menambahkan suatu baris dengan suatu kelipatan dari baris yang lain.

Operasi-operasi ini tidak mengubah kumpulan solusi. Oleh karena itu, jika tujuan seseorang adalah untuk menyelesaikan sistem persamaan linear, penggunaan operasi baris ini dapat membuat masalah menjadi lebih mudah

## Contoh soal eliminasi gaussian

contoh soal :

\begin{align*} 
    8x_1 + 9x_2 + x_3 &= 19\\
    x_1  + 2x_2 + 3x_3 &= 9\\
    2x_1 + x_2  + x_3 &= 5
\end{align*}

ubah menjadi bentuk matrix

\begin{bmatrix}
8 & 9 & 1 & 19\\
1 & 2 & 3 & 9\\
2 & 1 & 1 & 5
\end{bmatrix}

In [1]:
# import library numpy
import numpy as np

# masukkan nilai yang ada pada matrix
A=np.array([[8,9,1,19],[1,2,3,9],[2,1,1,5]])

In [2]:
def RowSwap(A,k,l):
# =============================================================================
#     A adalah sebuah NumPy array.  RowSwap akan menghasilkan duplicate dari 
#     array dengan baris k dan l di tukar
# =============================================================================
    m = A.shape[0]  # m adalah nomor baris di A
    n = A.shape[1]  # n adalah nomor kolom di A

    B = np.copy(A).astype('float64')

    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp

    return B

def RowScale(A,k,scale):
# =============================================================================
#     A adalah sebuah NumPy array.  RowScale akan menghasilkan duplicate dari 
#     array dengan baris k di kali dengan skalar bukan 0
# =============================================================================
    m = A.shape[0]  # m adalah nomor baris di A
    n = A.shape[1]  # n adalah nomor kolom di A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale

    return B

def RowAdd(A,k,l,scale):
# =============================================================================
#     A adalah sebuah NumPy array.  RowAdd akan menghasilkan duplicate dari 
#     array dengan baris k akan di kali dengan 'scale' bukan 0. lalu nilai
#     baris l akan di tambah dengan nilai baris k yang sudah dikalikan  
# =============================================================================
    m = A.shape[0]  # m adalah nomor baris di A
    n = A.shape[1]  # n adalah nomor kolom di A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[l][j] += B[k][j]*scale

    return B

In [3]:
print(A,'\n')

# tukar posisi baris 1 dan baris 2
A = RowSwap(A,0,1)
print(A,'\n')

# baris 1 di kali -8 lalu ditambahkan ke baris 2
A1 = RowAdd(A,0,1,-8)
print(A1,'\n')

# baris 1 di kali -2 lalu ditambahkan ke baris 3
A2 = RowAdd(A1,0,2,-2)
print(A2,'\n')

# baris 2 di kalikan dengan -1/7
A3 = RowScale(A2,1,-1/7)
print(A3,'\n')

# baris 2 di kalikan 3 lalu ditambahkan ke baris 3
A4 = RowAdd(A3,1,2,3)
print(A4,'\n')

# baris 3 di  kalikan dengan 1/4.85714286
A5 = RowScale(A4,2,1/4.85714286)
print(A5)

[[ 8  9  1 19]
 [ 1  2  3  9]
 [ 2  1  1  5]] 

[[ 1.  2.  3.  9.]
 [ 8.  9.  1. 19.]
 [ 2.  1.  1.  5.]] 

[[  1.   2.   3.   9.]
 [  0.  -7. -23. -53.]
 [  2.   1.   1.   5.]] 

[[  1.   2.   3.   9.]
 [  0.  -7. -23. -53.]
 [  0.  -3.  -5. -13.]] 

[[  1.           2.           3.           9.        ]
 [ -0.           1.           3.28571429   7.57142857]
 [  0.          -3.          -5.         -13.        ]] 

[[ 1.          2.          3.          9.        ]
 [-0.          1.          3.28571429  7.57142857]
 [ 0.          0.          4.85714286  9.71428571]] 

[[ 1.          2.          3.          9.        ]
 [-0.          1.          3.28571429  7.57142857]
 [ 0.          0.          1.          2.        ]]


## Subtitusi balik


setelah menggunakan eliminasi gaussian dan di bulatkan di peroleh hasil sebagai berikut:

\begin{bmatrix} 
1 & 2 & 3 & 9\\
0 & 1 & 3.2 & 7.5\\
0 & 0 & 1 & 2
\end{bmatrix}

ubah menjadi bentuk persamaan 

\begin{align*} 
    x_1 + 2x_2 + 3x_3 &= 9\\
    x_2 + 3.2x_3 &= 7.5\\
    x_3 &= 2
\end{align*}

untuk mencari nilai x yang lain di gunakan metode substitusi balik

In [4]:
x3 = 2
print('x3 =',x3)

# di peroleh nilai x3 = 2
# nilai x3 akan di masukkan ke persamaan kedua

x2 = 7.5 - 3.2 *x3
print('x2 =',round(x2))

# di peroleh nilai x2 = 1 
# nilai x3 dam x2 di masukkan ke persamaan pertama

x1 = 9 - 2*x2 - 3*x3
print('x1 =', round(x1))

# di peroleh nilai x1 = 1

x3 = 2
x2 = 1
x1 = 1


hasil dari sistem persamaan berikut:


\begin{align*} 
    8x_1 + 9x_2 + x_3 &= 19\\
    x_1  + 2x_2 + 3x_3 &= 9\\
    2x_1 + x_2  + x_3 &= 5
\end{align*}

diperoleh nilai dari x1, x2 dan x3 sebagai berikut:

\begin{align*} 
    x_1 &= 1\\
    x_2 &= 1\\
    x_3 &= 2
\end{align*}

In [7]:
AI = np.array([[2,2,1,1,0,0],[4,2,3,0,1,0],[1,3,-1,0,0,1]])
print(AI)

# AI1 = RowScale(AI,0,1/2)
# print(AI1)

# AI2 = RowAdd(AI1,0,1,-4)
# print(AI2)

# AI3 = RowAdd(AI2,0,2,-1)
# print(AI3)

# AI4 = RowScale(AI3,1,-1/2)
# print(AI4)

# AI5 = RowAdd(AI4,1,2,-2)
# print(AI5)

# AI6 = RowScale(AI5,2,-2)
# print(AI6)

# AI7 = RowAdd(AI6,1,0,-1)
# print(AI7)

# AI8 = RowAdd(AI7,2,1,0.5) 
# print(AI8)

# AI9 = RowAdd(AI8,2,0,-1)
# print(AI9)

Ainvers = np.array([[-5.5,2.5,2],[3.5,-1.5,-1],[5,-2,-2]])
Mat = np.array([[2,2,1],[4,2,3],[1,3,-1]])
B = np.array([[9],[17],[5]])
dot1 = np.dot(Ainvers,Mat)
print(Ainvers)
print(dot1)


[[ 2  2  1  1  0  0]
 [ 4  2  3  0  1  0]
 [ 1  3 -1  0  0  1]]
[[-5.5  2.5  2. ]
 [ 3.5 -1.5 -1. ]
 [ 5.  -2.  -2. ]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
