# Matrix

## Operasi matrix menggunakan library numpy

matriks adalah susunan bilangan-bilangan berbentuk persegi panjang yang diatur dalam baris atau kolom dengan dibatasi kurung. Bilangan yang tersusun dalam matriks disebut elemen/unsur matriks. Baris adalah susunan bilangan-bilangan yang mendatar (horizontal), sedangkan kolom adalah susunan bilangan-bilangan yang tegak (vertikal). 

Ordo matriks adalah banyaknya elemen baris dan banyaknya elemen kolom dari suatu matriks. Jika sebuah matriks memiliki i baris dan j kolom, maka matriks tersebut berordo i x j, dapat dituliskan Ai.j

In [1]:
# import library numpy
import numpy as np

In [2]:
gunakan np.array([matrix]) untuk membuat matrix dengan nilai yang dapat diisi sendiri

SyntaxError: invalid syntax (832924179.py, line 1)

In [3]:
A = np.array([[1,3],[2,1]])
B = np.array([[3,0,4],[-1,-2,-1]])
C = np.array([[-2,1],[4,1]])
D = np.array([[2],[6]])

print("Matrix A")
print(A,"\n")
print("Matrix B")
print(B,"\n")
print("Matrix C")
print(C,"\n")
print("Matrix D")
print(D,"\n")

Matrix A
[[1 3]
 [2 1]] 

Matrix B
[[ 3  0  4]
 [-1 -2 -1]] 

Matrix C
[[-2  1]
 [ 4  1]] 

Matrix D
[[2]
 [6]] 



gunakan np.random.randint(n, size(=i,j)) untuk membuat matrix debgan nilai interger acak 0-n dan memiliki baris i dan kolom j

In [4]:
E = np.random.randint(10,size=(2,2))
F = np.random.randint(10,size=(3,2))
G = np.random.randint(10,size=(3,3))
print("Matrix F")
print(E,"\n")
print("Matrix E")
print(F,"\n")
print("Matrix G")
print(G,"\n")

[[4 0]
 [1 5]] 

[[2 4]
 [5 5]
 [6 7]] 

[[8 2 9]
 [1 6 5]
 [1 1 9]] 



untuk mengecek panjang baris dan kolom dapat menggunakan np.shape atau len

In [13]:
print("baris dan kolom matrix A\n",np.shape(A))

print("baris dan kolom matrix B\n", len(B),len(B[0]))


baris dan kolom matrix A
 (2, 2)
baris dan kolom matrix B
 2 3


## Operasi matrix

penjumlahan

Syarat penjumlahan dan pengurangan matriks yaitu : jika terdapat dua matriks, misal matriks A dan B, yang memiliki ordo sama, maka elemen-elemen yang seletak dapat dijumlahkan atau dikurangkan.

contoh :

In [22]:
print("matrix A")
print(A,"\n")
print("matrix C")
print(C,"\n")

ac = A + C
print("hasil matrix A+C")
print(ac)

matrix A
[[1 3]
 [2 1]] 

matrix C
[[-2  1]
 [ 4  1]] 

hasil matrix A+C
[[-1  4]
 [ 6  2]]


## perkalian

Pada operasi perkalian skalar, sebuah matriks dikalikan dengan bilangan skalar. Jika diketahui A merupakan suatu matriks dan K merupakan bilangan real, maka hasil perkalian K dengan matriks A adalah matriks yang diperoleh dengan mengalikan setiap elemen A dengan K.

contoh :

In [27]:
# perkalian matrix dengan skalar

# k adalah skalar dan A adalh matrix
k = 2
Ak = k * A
print("matrix A")
print(A,"\n")
print("skalar k")
print(k,"\n")
print("hasil perkalian matriks A dengan skalar k ")
print(Ak, "\n")


matrix A
[[1 3]
 [2 1]] 

skalar k
2 

hasil perkalian matriks A dengan skalar k 
[[2 6]
 [4 2]] 



Perkalian Dua Matriks

Berbeda dengan perkalian skalar yang hanya mengalikan setiap elemen matriks dengan bilangan skalar, perkalian dua matriks memiliki aturan tersendiri.  Syarat dua buah matriks, misal matriks A dan matriks B, dapat dikalikan adalah jika banyaknya kolom matriks A sama dengan banyaknya baris matriks B.


## perkalian matriks tanpa menggunakan perunlangan

In [28]:
listA = [
    [3,4],
    [2,5],
    [1,3]
    ]

listB = [
    [2,3,1],
    [1,4,3],
    ]
  
print("Matriks A",listA,"\n")
print("MAtriks B",listB,"\n")

print("panjang baris dan kolom")
print("Matriks A")
print(len(listA),len(listA[0]),"\n")
print("Matriks B")
print(len(listB),len(listB[0]),"\n")

# n adalah panjang baris matrix listA
n = len(listA)

# adalah panjang kolom matrix listA dan panjang baris matrix listB
m = len(listA[0])

# p adalah panjang baris matrix listB
p = len(listB[0])

hasil = []
# perulangan terjadi sebanyak panjang baris listA
for i in range(0,n):
  hasil1 = []
  # perulangan terjadi sebanyak panjang baris listB
  for j in range(0,p):
    jumlah = 0
    for k in range(0,m):
      jumlah += listA[i][k] * listB[k][j]
    hasil1.append(jumlah)
  hasil.append(hasil1)
print("hasil dari perkalian matrix")
print(hasil,"\n")

Matriks A [[3, 4], [2, 5], [1, 3]] 

MAtriks B [[2, 3, 1], [1, 4, 3]] 

panjang baris dan kolom
Matriks A
3 2 

Matriks B
2 3 

hasil dari perkalian matrix
[[10, 25, 15], [9, 26, 17], [5, 15, 10]] 



perkalian dua matriks menggunakan library numpy

In [30]:
MatriksA = np.array(([3,4],[2,5],[1,3]))
MatriksB = np.array(([2,3,1],[1,4,3]))

print(MatriksA,"\n")
print(MatriksB,"\n")

dot1 = np.dot(MatriksA,MatriksB)
dot2 = MatriksA.dot(MatriksB)

print(dot1,"\n")
print(dot2,"\n")

[[3 4]
 [2 5]
 [1 3]] 

[[2 3 1]
 [1 4 3]] 

[[10 25 15]
 [ 9 26 17]
 [ 5 15 10]] 

[[10 25 15]
 [ 9 26 17]
 [ 5 15 10]] 

