# Matrix

matriks adalah susunan bilangan-bilangan berbentuk persegi panjang yang diatur dalam baris atau kolom dengan dibatasi kurung. Bilangan yang tersusun dalam matriks disebut elemen/unsur matriks. Baris adalah susunan bilangan-bilangan yang mendatar (horizontal), sedangkan kolom adalah susunan bilangan-bilangan yang tegak (vertikal). 

Ordo matriks adalah banyaknya elemen baris dan banyaknya elemen kolom dari suatu matriks. Jika sebuah matriks memiliki i baris dan j kolom, maka matriks tersebut berordo i x j, dapat dituliskan Ai.j

## Penggunaan library numpy pada matrix

In [1]:
# import library numpy
import numpy as np

np.array([matrix]) digunakan  untuk membuat matrix dengan nilai yang dapat diisi sendiri

In [2]:
A = np.array([[1,3],[2,1]])
B = np.array([[3,0,4],[-1,-2,-1]])
C = np.array([[-2,1],[4,1]])
D = np.array([[2],[6]])

print("Matrix A")
print(A,"\n")
print("Matrix B")
print(B,"\n")
print("Matrix C")
print(C,"\n")
print("Matrix D")
print(D,"\n")

Matrix A
[[1 3]
 [2 1]] 

Matrix B
[[ 3  0  4]
 [-1 -2 -1]] 

Matrix C
[[-2  1]
 [ 4  1]] 

Matrix D
[[2]
 [6]] 



np.random.randint(n, size(=i,j)) digunakan untuk membuat matrix dengan nilai interger acak 0-n yang mempunyai baris i dan kolom j

In [3]:
E = np.random.randint(10,size=(2,2))
F = np.random.randint(10,size=(3,2))
G = np.random.randint(10,size=(3,3))
print("Matrix F")
print(E,"\n")
print("Matrix E")
print(F,"\n")
print("Matrix G")
print(G,"\n")

Matrix F
[[2 5]
 [9 0]] 

Matrix E
[[9 9]
 [3 4]
 [2 8]] 

Matrix G
[[1 2 5]
 [5 4 7]
 [2 8 7]] 



untuk mengecek panjang baris dan kolom dapat menggunakan np.shape atau len

In [4]:
print("baris dan kolom matriks A\n",np.shape(A))

print("baris dan kolom matriks B\n", len(B),len(B[0]))


baris dan kolom matriks A
 (2, 2)
baris dan kolom matriks B
 2 3


## Operasi matriks

penjumlahan

Konsep penjumlahan matriks sama seperti penjumlahan pada bilangan. Salah satu syarat penjumlahan ini adalah matriks yang dijumlahkan memiliki ordo yang sama. Operasi penjumlahan ini juga memenuhi sifat-sifat berikut.
1. Sifat komutatif\
Pada sifat ini berlaku A + B = B + A.
2. Sifat asosiatif\
Pada sifat ini berlaku (A + B) + C = A +(B + C)
3. Matriks nol\
Pada sifat ini berlaku A + 0 = A
4. Jika dijumlahkan dengan lawannya akan menghasilkan matriks nol, yaitu A + (-A) = 0. 

contoh :

In [5]:
print("matriks A")
print(A,"\n")
print("matriks C")
print(C,"\n")

ac = A + C
print("hasil matriks A + C")
print(ac)

matriks A
[[1 3]
 [2 1]] 

matriks C
[[-2  1]
 [ 4  1]] 

hasil matriks A + C
[[-1  4]
 [ 6  2]]


Pengurangan

Konsep pengurangan pada matriks sama seperti penjumlahan, yaitu mengurangkan elemen yang letaknya sama atau seletak. Salah satu syarat yang harus dipenuhi juga sama, yaitu memiliki ordo yang sama. Pada pengurangan matriks ini, tidak berlaku sifat-sifat seperti halnya penjumlahan. Adapun contoh soal pengurangan matriks adalah sebagai berikut.

In [6]:
print("matriks C")
print(C,"\n")
print("matriks A")
print(A,"\n")

ca = C - A
print("hasil matriks C - A")
print(ca)

matriks C
[[-2  1]
 [ 4  1]] 

matriks A
[[1 3]
 [2 1]] 

hasil matriks C - A
[[-3 -2]
 [ 2  0]]


perkalian

1. perkalian matriks dengan skalar\
Pada operasi perkalian skalar, sebuah matriks dikalikan dengan bilangan skalar. Jika diketahui A merupakan suatu matriks dan K merupakan bilangan real, maka hasil perkalian K dengan matriks A adalah matriks yang diperoleh dengan mengalikan setiap elemen A dengan K.

    contoh :

In [7]:
# perkalian matrix dengan skalar

# k adalah skalar dan A adalh matrix
k = 2
Ak = k * A
print("matrix A")
print(A,"\n")
print("skalar k")
print(k,"\n")
print("hasil perkalian matriks A dengan skalar k ")
print(Ak, "\n")


matrix A
[[1 3]
 [2 1]] 

skalar k
2 

hasil perkalian matriks A dengan skalar k 
[[2 6]
 [4 2]] 



2. Perkalian Dua Matriks\
Berbeda dengan perkalian skalar yang hanya mengalikan setiap elemen matriks dengan bilangan skalar, perkalian dua matriks memiliki aturan tersendiri.  Syarat dua buah matriks, misal matriks A dan matriks B, dapat dikalikan adalah jika banyaknya kolom matriks A sama dengan banyaknya baris matriks B.

    Perkalian ini memenuhi sifat-sifat berikut.
    1. Sifat asosiatif\
    Pada sifat ini, berlaku (A × B) × C= A × (B × C)
    2. Sifat distributif\
    Pada sifat ini, berlaku A × (B + C) = (A × B) + (A × C)


## Tugas perkalian dua matriks 
perkalian dua matriks menggunakan perulangan

In [8]:
listA = [
    [3,4],
    [2,5],
    [1,3]
    ]

listB = [
    [2,3,1],
    [1,4,3],
    ]
  
print("Matriks A",listA,"\n")
print("MAtriks B",listB,"\n")

print("panjang baris dan kolom")
print("Matriks A")
print(len(listA),len(listA[0]),"\n")
print("Matriks B")
print(len(listB),len(listB[0]),"\n")

# n adalah panjang baris matrix listA
n = len(listA)

# adalah panjang kolom matrix listA dan panjang baris matrix listB
m = len(listA[0])

# p adalah panjang baris matrix listB
p = len(listB[0])

hasil = []
# perulangan terjadi sebanyak panjang baris listA
for i in range(0,n):
  hasil1 = []
  # perulangan terjadi sebanyak panjang baris listB
  for j in range(0,p):
    jumlah = 0
    for k in range(0,m):
      jumlah += listA[i][k] * listB[k][j]
    hasil1.append(jumlah)
  hasil.append(hasil1)
print("hasil dari perkalian matrix")
print(hasil,"\n")

Matriks A [[3, 4], [2, 5], [1, 3]] 

MAtriks B [[2, 3, 1], [1, 4, 3]] 

panjang baris dan kolom
Matriks A
3 2 

Matriks B
2 3 

hasil dari perkalian matrix
[[10, 25, 15], [9, 26, 17], [5, 15, 10]] 



perkalian dua matriks menggunakan library numpy

In [9]:
MatriksA = np.array(([3,4],[2,5],[1,3]))
MatriksB = np.array(([2,3,1],[1,4,3]))

print(MatriksA,"\n")
print(MatriksB,"\n")

dot1 = np.dot(MatriksA,MatriksB)
dot2 = MatriksA.dot(MatriksB)

print(dot1,"\n")
print(dot2,"\n")

[[3 4]
 [2 5]
 [1 3]] 

[[2 3 1]
 [1 4 3]] 

[[10 25 15]
 [ 9 26 17]
 [ 5 15 10]] 

[[10 25 15]
 [ 9 26 17]
 [ 5 15 10]] 

